In [3]:
import pandas as pd
import numpy as np
import glob
import os
import re
# Visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:


dataset_path = "../../../EOI_data/**/*.csv"
all_files = glob.glob(dataset_path, recursive=True)

# Filter: exclude files dengan nama diawali "MASTER_DATA_EOI"
pattern = re.compile(r"^MASTER_DATA_EOI")

filtered_files = [
    file for file in all_files if not pattern.match(os.path.basename(file))
]

df_list = []
for file in filtered_files:
    df_temp = pd.read_csv(file)
    df_list.append(df_temp)

# Gabungkan seluruh data
df_raw = pd.concat(df_list, ignore_index=True)

print(f"Total file ditemukan     : {len(all_files)}")
print(f"Total baris data awal    : {df_raw.shape[0]}")
df_raw.head()

Total file ditemukan     : 217
Total baris data awal    : 1745092

,As At Month,Visa Type,Occupation,EOI Status,Points,Count EOIs,Nominated State
0,03/2024,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,60,<20,ACT
1,03/2024,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,65,<20,ACT
2,03/2024,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,70,<20,ACT
3,03/2024,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,75,<20,ACT
4,03/2024,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,80,<20,ACT

In [5]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1745092 entries, 0 to 1745091
Data columns (total 7 columns):
 #   Column           Dtype
---  ------           -----
 0   As At Month      object
 1   Visa Type        object
 2   Occupation       object
 3   EOI Status       object
 4   Points           int64
 5   Count EOIs       object
 6   Nominated State  object
dtypes: int64(1), object(6)
memory usage: 93.2+ MB

In [6]:
df_raw["Count EOIs"].value_counts()

Count EOIs
<20     1516813
20         8675
21         8164
22         7762
23         7242
         ...
1200          1
1214          1
917           1
1176          1
1280          1
Name: count, Length: 1100, dtype: int64

In [7]:
df_raw["Count EOIs"] = df_raw["Count EOIs"].replace("<20", 10)

In [8]:
df_raw['Visa Type'].value_counts()

Visa Type
491SNR State or Territory Nominated - Regional    891253
190SAS Skilled Australian Sponsored               849223
189PTS Points-Tested Stream                         3660
491FSR Family Sponsored - Regional                   956
Name: count, dtype: int64

In [9]:
df_raw.isnull().sum()

As At Month        0
Visa Type          0
Occupation         0
EOI Status         0
Points             0
Count EOIs         0
Nominated State    0
dtype: int64

In [10]:
df_raw.duplicated().sum()

np.int64(0)

In [11]:


df_raw['EOI Status'].value_counts()

EOI Status
SUBMITTED    821578
CLOSED       612674
LODGED       172142
HOLD          94092
INVITED       44606
Name: count, dtype: int64

In [10]:
df_raw["Visa Type"].value_counts()

Visa Type
491SNR State or Territory Nominated - Regional    891253
190SAS Skilled Australian Sponsored               849223
189PTS Points-Tested Stream                         3660
491FSR Family Sponsored - Regional                   956
Name: count, dtype: int64

In [18]:
df_filtered = df_raw[df_raw["EOI Status"].isin(["SUBMITTED","LODGED"])]

In [19]:
df_filtered

,As At Month,Visa Type,Occupation,EOI Status,Points,Count EOIs,Nominated State
0,03/2024,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,60,10,ACT
1,03/2024,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,65,10,ACT
2,03/2024,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,70,10,ACT
3,03/2024,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,75,10,ACT
4,03/2024,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,80,10,ACT
...,...,...,...,...,...,...,...
1745082,02/2026,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,80,10,WA
1745083,02/2026,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,85,10,WA
1745084,02/2026,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,90,10,WA
1745085,02/2026,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,95,10,WA
1745086,02/2026,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,100,10,WA

In [84]:
df_filtered.to_csv('df_eoi.csv')

In [20]:
feature_cols = [col for col in df_filtered.columns if col not in ["As At Month", "EOI Status"]]

# Temukan duplikat berdasarkan fitur saja
duplicates = df_filtered[df_filtered.duplicated(subset=feature_cols, keep=False)]
print(f"Jumlah baris duplikat: {len(duplicates)}")
duplicates.sort_values(feature_cols)

Jumlah baris duplikat: 888762

,As At Month,Visa Type,Occupation,EOI Status,Points,Count EOIs,Nominated State
179875,08/2024,189PTS Points-Tested Stream,133111 Construction Project Manager,SUBMITTED,95,10,ACT
179881,08/2024,189PTS Points-Tested Stream,133111 Construction Project Manager,LODGED,95,10,ACT
179927,08/2024,189PTS Points-Tested Stream,134111 Child Care Centre Manager,SUBMITTED,85,10,ACT
179929,08/2024,189PTS Points-Tested Stream,134111 Child Care Centre Manager,LODGED,85,10,ACT
179940,08/2024,189PTS Points-Tested Stream,134213 Primary Health Organisation Manager,SUBMITTED,70,10,ACT
...,...,...,...,...,...,...,...
1384053,11/2025,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,110,10,NSW
1479014,12/2025,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,110,10,NSW
1575177,01/2026,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,110,10,NSW
1672365,02/2026,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,110,10,NSW
1672366,02/2026,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,LODGED,110,10,NSW

In [21]:
df_filtered["Count EOIs"] = df_filtered["Count EOIs"].astype(int)

C:\Users\User\AppData\Local\Temp\ipykernel_5540\3622896026.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["Count EOIs"] = df_filtered["Count EOIs"].astype(int)

In [22]:
df_filtered["As At Month"] = pd.to_datetime(df_filtered["As At Month"])

C:\Users\User\AppData\Local\Temp\ipykernel_5540\532193848.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_filtered["As At Month"] = pd.to_datetime(df_filtered["As At Month"])
C:\Users\User\AppData\Local\Temp\ipykernel_5540\532193848.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["As At Month"] = pd.to_datetime(df_filtered["As At Month"])

In [12]:
df_filtered

,As At Month,Visa Type,Occupation,EOI Status,Points,Count EOIs,Nominated State
0,2024-03-01,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,60,10,ACT
1,2024-03-01,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,65,10,ACT
2,2024-03-01,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,70,10,ACT
3,2024-03-01,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,75,10,ACT
4,2024-03-01,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,SUBMITTED,80,10,ACT
...,...,...,...,...,...,...,...
1745082,2026-02-01,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,80,10,WA
1745083,2026-02-01,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,85,10,WA
1745084,2026-02-01,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,90,10,WA
1745085,2026-02-01,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,95,10,WA
1745086,2026-02-01,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,100,10,WA

In [23]:
df_filtered.loc[df_filtered["Occupation"].duplicated(), "Occupation"].nunique()

487

In [14]:
df_filtered["EOI Status"].value_counts()

EOI Status
SUBMITTED    821578
LODGED       172142
Name: count, dtype: int64

In [15]:
df_filtered['Occupation'].nunique()

489

In [24]:
kolom_kategorikal = df_filtered.select_dtypes(include=["object"]).columns.tolist()
if "Occupation" and "EOI Status" in kolom_kategorikal:
    kolom_kategorikal.remove("Occupation")
    kolom_kategorikal.remove("EOI Status")

In [25]:
kolom_kategorikal

['Visa Type', 'Nominated State']

In [26]:
df_encoded = pd.get_dummies(df_filtered,columns=kolom_kategorikal,dtype=int)
df_encoded

,As At Month,Occupation,EOI Status,Points,Count EOIs,Visa Type_189PTS Points-Tested Stream,Visa Type_190SAS Skilled Australian Sponsored,Visa Type_491FSR Family Sponsored - Regional,Visa Type_491SNR State or Territory Nominated - Regional,Nominated State_ACT,Nominated State_NSW,Nominated State_NT,Nominated State_QLD,Nominated State_SA,Nominated State_TAS,Nominated State_VIC,Nominated State_WA
0,2024-03-01,131112 Sales and Marketing Manager,SUBMITTED,60,10,0,1,0,0,1,0,0,0,0,0,0,0
1,2024-03-01,131112 Sales and Marketing Manager,SUBMITTED,65,10,0,1,0,0,1,0,0,0,0,0,0,0
2,2024-03-01,131112 Sales and Marketing Manager,SUBMITTED,70,10,0,1,0,0,1,0,0,0,0,0,0,0
3,2024-03-01,131112 Sales and Marketing Manager,SUBMITTED,75,10,0,1,0,0,1,0,0,0,0,0,0,0
4,2024-03-01,131112 Sales and Marketing Manager,SUBMITTED,80,10,0,1,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1745082,2026-02-01,639211 Retail Buyer,SUBMITTED,80,10,0,0,0,1,0,0,0,0,0,0,0,1
1745083,2026-02-01,639211 Retail Buyer,SUBMITTED,85,10,0,0,0,1,0,0,0,0,0,0,0,1
1745084,2026-02-01,639211 Retail Buyer,SUBMITTED,90,10,0,0,0,1,0,0,0,0,0,0,0,1
1745085,2026-02-01,639211 Retail Buyer,SUBMITTED,95,10,0,0,0,1,0,0,0,0,0,0,0,1
1745086,2026-02-01,639211 Retail Buyer,SUBMITTED,100,10,0,0,0,1,0,0,0,0,0,0,0,1

In [27]:
import category_encoders as ce
encoder = ce.BinaryEncoder(cols=["Occupation"])
df_encode2 = encoder.fit_transform(df_encoded)


aturan_label = {"SUBMITTED": 0, "LODGED": 1}

# 2. Terapkan aturan tersebut ke kolom 'EOI Status'
df_encode2["EOI Status"] = df_encode2["EOI Status"].map(aturan_label)

In [57]:
df_encode2['EOI Status']

0          0
1          0
2          0
3          0
4          0
          ..
1745082    0
1745083    0
1745084    0
1745085    0
1745086    0
Name: EOI Status, Length: 993720, dtype: int64

In [41]:
df_encode2

,As At Month,Occupation_0,Occupation_1,Occupation_2,Occupation_3,Occupation_4,Occupation_5,Occupation_6,Occupation_7,Occupation_8,...,Visa Type_491FSR Family Sponsored - Regional,Visa Type_491SNR State or Territory Nominated - Regional,Nominated State_ACT,Nominated State_NSW,Nominated State_NT,Nominated State_QLD,Nominated State_SA,Nominated State_TAS,Nominated State_VIC,Nominated State_WA
0,2024-03-01,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
1,2024-03-01,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
2,2024-03-01,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
3,2024-03-01,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
4,2024-03-01,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1745082,2026-02-01,0,1,1,0,1,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
1745083,2026-02-01,0,1,1,0,1,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
1745084,2026-02-01,0,1,1,0,1,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
1745085,2026-02-01,0,1,1,0,1,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1
1745086,2026-02-01,0,1,1,0,1,0,1,0,1,...,0,1,0,0,0,0,0,0,0,1

In [59]:
df_encode2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 993720 entries, 0 to 1745086
Data columns (total 25 columns):
 #   Column                                                    Non-Null Count   Dtype
---  ------                                                    --------------   -----
 0   As At Month                                               993720 non-null  datetime64[ns]
 1   Occupation_0                                              993720 non-null  int64
 2   Occupation_1                                              993720 non-null  int64
 3   Occupation_2                                              993720 non-null  int64
 4   Occupation_3                                              993720 non-null  int64
 5   Occupation_4                                              993720 non-null  int64
 6   Occupation_5                                              993720 non-null  int64
 7   Occupation_6                                              993720 non-null  int64
 8   Occupation_7                                              993720 non-null  int64
 9   Occupation_8                                              993720 non-null  int64
 10  EOI Status                                                993720 non-null  int64
 11  Points                                                    993720 non-null  int64
 12  Count EOIs                                                993720 non-null  int64
 13  Visa Type_189PTS Points-Tested Stream                     993720 non-null  int64
 14  Visa Type_190SAS Skilled Australian Sponsored             993720 non-null  int64
 15  Visa Type_491FSR Family Sponsored - Regional              993720 non-null  int64
 16  Visa Type_491SNR State or Territory Nominated - Regional  993720 non-null  int64
 17  Nominated State_ACT                                       993720 non-null  int64
 18  Nominated State_NSW                                       993720 non-null  int64
 19  Nominated State_NT                                        993720 non-null  int64
 20  Nominated State_QLD                                       993720 non-null  int64
 21  Nominated State_SA                                        993720 non-null  int64
 22  Nominated State_TAS                                       993720 non-null  int64
 23  Nominated State_VIC                                       993720 non-null  int64
 24  Nominated State_WA                                        993720 non-null  int64
dtypes: datetime64[ns](1), int64(24)
memory usage: 197.1 MB

In [28]:
X = df_encode2.drop(columns=['EOI Status','As At Month']).values
y = df_encode2['EOI Status'].values

In [105]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 0, 1]])

In [13]:
from tensorflow.keras.models import load_model

X = dataset.drop(columns=['EOI_Skill_'])
y = dataset['EOI_Skill_Score']

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

def create_sequences(data, target, time_steps=10):
    X, y = [], []
    for i in range(len(data) - time_steps):
        X.append(data[i : (i + time_steps)])
        y.append(target[i + time_steps])
    return np.array(X), np.array(y)

def undersample_sequences(X, y):
    # Cari indeks untuk masing-masing kelas
    indices_class_0 = np.where(y == 0)[0]
    indices_class_1 = np.where(y == 1)[0]  # Misal Invited
    # ... ulangi untuk kelas lain

    # Tentukan jumlah sampel minimum (misal disamakan dengan jumlah kelas tersedikit)
    n_samples = len(indices_class_1)

    # Ambil sampel acak dari kelas mayoritas
    random_indices_0 = np.random.choice(indices_class_0, n_samples)

    # Gabungkan kembali
    new_indices = np.concatenate([random_indices_0, indices_class_1])

    return X[new_indices], y[new_indices]

# Asumsi df_encoded adalah DataFrame hasil Binary Encoding Anda
# Fitur = 9 kolom biner + fitur numerik lainnya

In [ ]:

def create_sequences(data , time_steps=10):
    X = []
    for i in range(len(data) - time_steps):
        X.append(data[i : (i + time_steps)])
    return np.array(X)

X_3d = create_sequences(X, time_steps=10)

In [29]:
# Membuat data 3D
X_3d, y_3d = create_sequences(X, y, time_steps=10)


X_3d_balanced, y_3d_balanced = undersample_sequences(X_3d, y_3d)


print(f"Shape Input: {X_3d.shape}")

Shape Input: (993710, 10, 23)

In [63]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_3d, y_3d, test_size=0.2, shuffle=False
)

In [65]:
model = Sequential(
    [
        # Layer LSTM pertama
        LSTM(64, input_shape=(X_train.shape[1], X_train.shape[2]), return_sequences=True),
        Dropout(0.2),
        # Layer LSTM kedua
        LSTM(32, return_sequences=False),
        Dropout(0.2),
        # Fully Connected Layer
        Dense(16, activation="relu"),
        # Output Layer (Gunakan 'sigmoid' untuk binary, 'softmax' untuk multi-class)
        Dense(1, activation="sigmoid"),
    ]
)

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
    
)
model.summary()

c:\Users\User\anaconda3\envs\myenv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_4 (LSTM)                   │ (None, 10, 64)         │        22,528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 10, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 35,489 (138.63 KB)

 Trainable params: 35,489 (138.63 KB)

 Non-trainable params: 0 (0.00 B)

In [66]:
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,  # Mengambil 20% data untuk validasi
    verbose=1,
    callbacks=early_stop
)

Epoch 1/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 119s 6ms/step - accuracy: 0.8861 - loss: 0.2674 - val_accuracy: 0.8822 - val_loss: 0.2728
Epoch 2/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 126s 6ms/step - accuracy: 0.9035 - loss: 0.2253 - val_accuracy: 0.9062 - val_loss: 0.2148
Epoch 3/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 132s 7ms/step - accuracy: 0.9109 - loss: 0.2072 - val_accuracy: 0.9089 - val_loss: 0.2058
Epoch 4/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 117s 6ms/step - accuracy: 0.9142 - loss: 0.1990 - val_accuracy: 0.9083 - val_loss: 0.2039
Epoch 5/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 116s 6ms/step - accuracy: 0.9162 - loss: 0.1944 - val_accuracy: 0.9131 - val_loss: 0.1976
Epoch 6/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 145s 6ms/step - accuracy: 0.9174 - loss: 0.1909 - val_accuracy: 0.9143 - val_loss: 0.1981
Epoch 7/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 120s 6ms/step - accuracy: 0.9183 - loss: 0.1886 - val_accuracy: 0.9169 - val_loss: 0.1901
Epoch 8/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 120s 6ms/step - accuracy: 0.9194 - loss: 0.1865 - val_accuracy: 0.9172 - val_loss: 0.1882
Epoch 9/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 118s 6ms/step - accuracy: 0.9199 - loss: 0.1844 - val_accuracy: 0.9182 - val_loss: 0.1888
Epoch 10/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 120s 6ms/step - accuracy: 0.9208 - loss: 0.1831 - val_accuracy: 0.9170 - val_loss: 0.1900
Epoch 11/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 120s 6ms/step - accuracy: 0.9212 - loss: 0.1820 - val_accuracy: 0.9190 - val_loss: 0.1867
Epoch 12/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 119s 6ms/step - accuracy: 0.9218 - loss: 0.1805 - val_accuracy: 0.9198 - val_loss: 0.1834
Epoch 13/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 123s 6ms/step - accuracy: 0.9221 - loss: 0.1795 - val_accuracy: 0.9184 - val_loss: 0.1855
Epoch 14/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 122s 6ms/step - accuracy: 0.9226 - loss: 0.1785 - val_accuracy: 0.9197 - val_loss: 0.1838
Epoch 15/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 144s 6ms/step - accuracy: 0.9229 - loss: 0.1773 - val_accuracy: 0.9174 - val_loss: 0.1848
Epoch 16/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 129s 6ms/step - accuracy: 0.9226 - loss: 0.1776 - val_accuracy: 0.9193 - val_loss: 0.1847
Epoch 17/20
19875/19875 ━━━━━━━━━━━━━━━━━━━━ 127s 6ms/step - accuracy: 0.9227 - loss: 0.1772 - val_accuracy: 0.9168 - val_loss: 0.1899

In [59]:
X_df = df_filtered.drop(columns=["EOI Status"])
y_df = df_filtered["EOI Status"]

In [60]:
X_train_df,X_test_df,y_train_df,y_test_df = train_test_split(X_df,y_df,test_size=0.2,shuffle=False)

In [103]:
X_train_df

,As At Month,Visa Type,Occupation,Points,Count EOIs,Nominated State
0,2024-03-01,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,60,10,ACT
1,2024-03-01,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,65,10,ACT
2,2024-03-01,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,70,10,ACT
3,2024-03-01,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,75,10,ACT
4,2024-03-01,190SAS Skilled Australian Sponsored,131112 Sales and Marketing Manager,80,10,ACT
...,...,...,...,...,...,...
1372178,2025-11-01,190SAS Skilled Australian Sponsored,233999 Engineering Professionals nec,60,10,NSW
1372179,2025-11-01,190SAS Skilled Australian Sponsored,233999 Engineering Professionals nec,65,45,NSW
1372180,2025-11-01,190SAS Skilled Australian Sponsored,233999 Engineering Professionals nec,70,89,NSW
1372181,2025-11-01,190SAS Skilled Australian Sponsored,233999 Engineering Professionals nec,75,93,NSW
1372182,2025-11-01,190SAS Skilled Australian Sponsored,233999 Engineering Professionals nec,80,94,NSW

In [69]:
y_test_df = y_test_df.map(aturan_label)

In [107]:
y_test_df

1372183    0
1372184    0
1372185    0
1372186    0
1372187    0
          ..
1745082    0
1745083    0
1745084    0
1745085    0
1745086    0
Name: EOI Status, Length: 198744, dtype: int64

In [39]:
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

In [36]:
y_pred = model.predict(X_test)

6211/6211 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step

In [71]:
y_pred[:10]

array([[8.8883974e-03],
       [8.5896558e-05],
       [2.6042997e-05],
       [1.3235881e-05],
       [6.3050784e-06],
       [4.0491063e-06],
       [3.9673873e-06],
       [9.2223881e-06],
       [2.4277238e-05],
       [2.1816797e-04]], dtype=float32)

In [70]:
model.save("model_lstm.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [71]:
model.save('model_lstm.keras')

In [37]:
y_pred_class = (y_pred > 0.5).astype(int)

In [40]:
y_pred_class = (y_pred > 0.5).astype(int)

print(classification_report(y_test, y_pred_class))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95    159427
           1       0.82      0.74      0.78     39315

    accuracy                           0.92    198742
   macro avg       0.88      0.85      0.86    198742
weighted avg       0.91      0.92      0.91    198742

In [95]:
y_pred_class

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [48]:
df_final = X_test_df.copy()
df_final["Actual_Status"] = y_test_df

In [53]:
y_pred_flat = y_pred.flatten()

In [ ]:
time_steps = 2  # Sesuaikan dengan jumlah look-back LSTM-mu

# 1. Potong bagian atas df_final agar sejajar dengan tebakan model
df_final = df_final.iloc[time_steps:].copy()

# Tinggal kita masukkan tebakan modelnya:
df_final["predicted_class"] = y_pred_class
df_final["y_pred probability"] = y_pred_flat

In [72]:
df_final

,Visa Type,Occupation,Points,Count EOIs,Nominated State,Actual_Status,predicted_class,y_pred probability
1372185,190SAS Skilled Australian Sponsored,233999 Engineering Professionals nec,95,51,NSW,0,0,0.000002
1372186,190SAS Skilled Australian Sponsored,233999 Engineering Professionals nec,100,10,NSW,0,0,0.000020
1372187,190SAS Skilled Australian Sponsored,233999 Engineering Professionals nec,105,10,NSW,0,0,0.063790
1372188,190SAS Skilled Australian Sponsored,233999 Engineering Professionals nec,65,10,NSW,1,1,0.568391
1372189,190SAS Skilled Australian Sponsored,233999 Engineering Professionals nec,90,10,NSW,1,1,0.988892
...,...,...,...,...,...,...,...,...
1745082,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,80,10,WA,0,0,0.000318
1745083,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,85,10,WA,0,0,0.000431
1745084,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,90,10,WA,0,0,0.000528
1745085,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,95,10,WA,0,0,0.003620
1745086,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,100,10,WA,0,0,0.019998

In [35]:
model = load_model('model_lstm.keras')

c:\Users\User\anaconda3\envs\myenv\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 12 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [80]:
# Pastikan y_test_2 sudah disiapkan (dipotong sesuai time_steps LSTM)
y_test_df2 = y_test_df.iloc[time_steps:]
X_test_df2 = X_test_df.iloc[time_steps:]

In [102]:
top_index = np.argmax(y_pred)
best_combination = X_test_df.iloc[top_index]
print(f"--- BARIS DENGAN PELUANG 'LODGED' TERTINGGI ---")
print(f"Probabilitas  : {y_pred[top_index][0] * 100:.2f}%")
print(f"Detail Fitur  :\n{best_combination}")

--- BARIS DENGAN PELUANG 'LODGED' TERTINGGI ---
Probabilitas  : 99.98%
Detail Fitur  :
As At Month                                   2026-01-01 00:00:00
Visa Type          491SNR State or Territory Nominated - Regional
Occupation                                  233211 Civil Engineer
Points                                                         70
Count EOIs                                                     10
Nominated State                                               QLD
Name: 1591506, dtype: object

In [ ]:
import pandas as pd

# Membuat salinan data dan menambahkan kolom probabilitas
results_df = X_test_df2.copy()
results_df["Probabilitas_Lodged"] = y_pred[:, 0]  # Sesuaikan indeks probabilitasnya

# Mencari indeks baris dengan nilai probabilitas tertinggi untuk setiap pekerjaan
idx_highest_per_occ = results_df.groupby("Occupation")["Probabilitas_Lodged"].idxmax()

# Mengambil baris berdasarkan indeks yang ditemukan
top_per_occupation_df = results_df.loc[idx_highest_per_occ]

# Mengurutkan dari probabilitas yang paling tinggi ke rendah
top_per_occupation_df = top_per_occupation_df.sort_values(
    by="Probabilitas_Lodged", ascending=False
)

print("--- BARIS DENGAN PELUANG 'LODGED' PER PEKERJAAN dari November 2025 - Februari 2026 ---")
display(top_per_occupation_df)

--- BARIS DENGAN PELUANG 'LODGED' PER PEKERJAAN dari November 2025 - Februari 2026 ---

,As At Month,Visa Type,Occupation,Points,Count EOIs,Nominated State,Probabilitas_Lodged
1591508,2026-01-01,491SNR State or Territory Nominated - Regional,233211 Civil Engineer,80,10,QLD,0.999764
1400095,2025-11-01,491SNR State or Territory Nominated - Regional,233512 Mechanical Engineer,85,10,QLD,0.999697
1512410,2025-12-01,491SNR State or Territory Nominated - Regional,351311 Chef,85,10,SA,0.999650
1429455,2025-11-01,190SAS Skilled Australian Sponsored,241111 Early Childhood (Pre-primary School) Te...,75,10,VIC,0.999609
1726413,2026-02-01,491SNR State or Territory Nominated - Regional,233311 Electrical Engineer,85,10,VIC,0.999605
...,...,...,...,...,...,...,...
1567916,2026-01-01,491SNR State or Territory Nominated - Regional,121318 Pig Farmer,75,10,NSW,0.027083
1373542,2025-11-01,190SAS Skilled Australian Sponsored,253516 Paediatric Surgeon,90,10,NSW,0.024726
1498484,2025-12-01,491SNR State or Territory Nominated - Regional,332111 Floor Finisher,70,10,QLD,0.014253
1554898,2026-01-01,491SNR State or Territory Nominated - Regional,121211 Cotton Grower,100,10,ACT,0.013658
1722879,2026-02-01,190SAS Skilled Australian Sponsored,322113 Farrier,80,10,VIC,0.007164

In [ ]:

# 1. Buat salinan data keseluruhan
results_df = df_filtered.copy()

# 2. Filter hanya baris yang statusnya 'LODGED'
lodge_only_df = results_df[results_df["EOI Status"] == "LODGED"]

# 3. Hitung jumlah 'LODGED' per pekerjaan (Occupation)
df_lodged_occup = lodge_only_df["Occupation"].value_counts().reset_index()
df_lodged_occup.columns = ["Pekerjaan (Occupation)", "LODGE_count"]
print("--- JUMLAH  'LODGE' BERDASARKAN PEKERJAAN ---")
display(df_lodged_occup)

--- JUMLAH  'LODGE' BERDASARKAN PEKERJAAN ---

                     Pekerjaan (Occupation)  LODGE_count
0               221111 Accountant (General)         2954
1                               351311 Chef         2667
2               261111 ICT Business Analyst         2629
3                     233211 Civil Engineer         2626
4                233512 Mechanical Engineer         2399
..                                      ...          ...
421                     253312 Cardiologist            2
422  241512 Teacher of the Hearing Impaired            2
423               253516 Paediatric Surgeon            2
424               362213 Landscape Gardener            2
425                        361114 Zookeeper            1

[426 rows x 2 columns]